{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-peg-parser/1.0.0-SNAPSHOT/kotlin-peg-parser-1.0.0-SNAPSHOT.module",
    "group": "mirrg.xarpite",
    "module": "kotlin-peg-parser",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-peg-parser-linuxX64Main-1.0.0-SNAPSHOT.klib",
          "url": "kotlin-peg-parser-linuxx64-1.0.0-SNAPSHOT.klib",
          "size": 66477,
          "sha512": "1cc22dbe26e92efea67768d2cbb5b502136c8f37e04dbd5d985cc1f89cb76b683ff67e8acdfb83e58b3170e84042e080cec6ac6cbb8b4567efc8ecd87566b4f9",
          "sha256": "8b9308add77211127618182a241ff03136abb76cb2fbd81d1e4824cad17c8fc0",
          "sha1": "4b05d4262bfc4dbd5db9c7e18dcf76fff3e23599",
          "md5": "8f279de12c9c78c7e5227eb2d752b4ed"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-peg-parser-linuxx64-1.0.0-SNAPSHOT-sources.jar",
          "url": "kotlin-peg-parser-linuxx64-1.0.0-SNAPSHOT-sources.jar",
          "size": 11861,
          "sha512": "263c491633e52b23a0e88c07fd82ac7be3ee10917bd234ed5150d26ac114811e673bfc68f658d98448a56f749940175a734c20b722d41202211477caab4b1bee",
          "sha256": "17c42e651b0a64df578104b367b6c31e90bc344062cd957f2209519e9bf390a8",
          "sha1": "338b0eac8d45305a88be20caf4c3a3c181998c5c",
          "md5": "097d666d8811da727bd5d54090f67741"
        }
      ]
    }
  ]
}
