{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-peg-parser/1.0.3/kotlin-peg-parser-1.0.3.module",
    "group": "io.github.mirrgieriana.xarpite",
    "module": "kotlin-peg-parser",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-peg-parser-linuxX64Main-1.0.3.klib",
          "url": "kotlin-peg-parser-linuxx64-1.0.3.klib",
          "size": 66508,
          "sha512": "bb7aae315dff18f070a79e1fb8ab436c6da17722281d270884dc5910775bca2f66b9c651f1f4677073600315dd5994c968ecd6dd464d58d4f5b8d2f5d2e9a910",
          "sha256": "bb2689e14e86962c3cf54ff0c18374494ae8231a0b79ea718c35c5c63a7872f2",
          "sha1": "252c16914764738711618173c850edcc4dcc7f2c",
          "md5": "a429ac72105d513b5811f32ca9d82469"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-peg-parser-linuxx64-1.0.3-sources.jar",
          "url": "kotlin-peg-parser-linuxx64-1.0.3-sources.jar",
          "size": 11861,
          "sha512": "263c491633e52b23a0e88c07fd82ac7be3ee10917bd234ed5150d26ac114811e673bfc68f658d98448a56f749940175a734c20b722d41202211477caab4b1bee",
          "sha256": "17c42e651b0a64df578104b367b6c31e90bc344062cd957f2209519e9bf390a8",
          "sha1": "338b0eac8d45305a88be20caf4c3a3c181998c5c",
          "md5": "097d666d8811da727bd5d54090f67741"
        }
      ]
    }
  ]
}
