{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-peg-parser/1.0.0-SNAPSHOT/kotlin-peg-parser-1.0.0-SNAPSHOT.module",
    "group": "mirrg.xarpite",
    "module": "kotlin-peg-parser",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-peg-parser-js-1.0.0-SNAPSHOT.klib",
          "url": "kotlin-peg-parser-js-1.0.0-SNAPSHOT.klib",
          "size": 66419,
          "sha512": "1b172c83287e45a005fdd20a7054a89ac7c5aae474fc1285de583bffbef6bd7024e62f6f87878e06c27824ab82d488226c93755a827dc116d713affc93db39b9",
          "sha256": "7a8c6a893dfbe2ffbffaaa4ae73664547aa540c81a6ec2c5b39e2dcabc2f4364",
          "sha1": "a97b5e893b6fad0b5ad113cf58cf226d6b0826f6",
          "md5": "db9b1cc7f93d76303f5fe54f539eb8b5"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-peg-parser-js-1.0.0-SNAPSHOT.klib",
          "url": "kotlin-peg-parser-js-1.0.0-SNAPSHOT.klib",
          "size": 66419,
          "sha512": "1b172c83287e45a005fdd20a7054a89ac7c5aae474fc1285de583bffbef6bd7024e62f6f87878e06c27824ab82d488226c93755a827dc116d713affc93db39b9",
          "sha256": "7a8c6a893dfbe2ffbffaaa4ae73664547aa540c81a6ec2c5b39e2dcabc2f4364",
          "sha1": "a97b5e893b6fad0b5ad113cf58cf226d6b0826f6",
          "md5": "db9b1cc7f93d76303f5fe54f539eb8b5"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-peg-parser-js-1.0.0-SNAPSHOT-sources.jar",
          "url": "kotlin-peg-parser-js-1.0.0-SNAPSHOT-sources.jar",
          "size": 11861,
          "sha512": "263c491633e52b23a0e88c07fd82ac7be3ee10917bd234ed5150d26ac114811e673bfc68f658d98448a56f749940175a734c20b722d41202211477caab4b1bee",
          "sha256": "17c42e651b0a64df578104b367b6c31e90bc344062cd957f2209519e9bf390a8",
          "sha1": "338b0eac8d45305a88be20caf4c3a3c181998c5c",
          "md5": "097d666d8811da727bd5d54090f67741"
        }
      ]
    }
  ]
}
