{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mirrgieriana.xarpite",
    "module": "kotlin-peg-parser",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-peg-parser-metadata-1.0.0-SNAPSHOT.jar",
          "url": "kotlin-peg-parser-1.0.0-SNAPSHOT.jar",
          "size": 15030,
          "sha512": "cc266ccfdaefedf4b14e2c8b072f75f886e8e4fbd58b980730a7a986cb3cc8b523969f5ae7cd92be5688da6deea24d96944bc1bb0d2b57a3913503b1293d6f1c",
          "sha256": "d5ac8d7d31ffcaa97fe0a1cddec49f58514bec834f6ab1a902b01d83daf801b3",
          "sha1": "262e8b2037a7e0c0a7179daec80e7307e12dcce1",
          "md5": "017f9b4abeb429d35dbfce8ae3b94691"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-peg-parser-kotlin-1.0.0-SNAPSHOT-sources.jar",
          "url": "kotlin-peg-parser-1.0.0-SNAPSHOT-sources.jar",
          "size": 11861,
          "sha512": "263c491633e52b23a0e88c07fd82ac7be3ee10917bd234ed5150d26ac114811e673bfc68f658d98448a56f749940175a734c20b722d41202211477caab4b1bee",
          "sha256": "17c42e651b0a64df578104b367b6c31e90bc344062cd957f2209519e9bf390a8",
          "sha1": "338b0eac8d45305a88be20caf4c3a3c181998c5c",
          "md5": "097d666d8811da727bd5d54090f67741"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-peg-parser-js/1.0.0-SNAPSHOT/kotlin-peg-parser-js-1.0.0-SNAPSHOT.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "kotlin-peg-parser-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-peg-parser-js/1.0.0-SNAPSHOT/kotlin-peg-parser-js-1.0.0-SNAPSHOT.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "kotlin-peg-parser-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-peg-parser-js/1.0.0-SNAPSHOT/kotlin-peg-parser-js-1.0.0-SNAPSHOT.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "kotlin-peg-parser-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-peg-parser-jvm/1.0.0-SNAPSHOT/kotlin-peg-parser-jvm-1.0.0-SNAPSHOT.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "kotlin-peg-parser-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-peg-parser-jvm/1.0.0-SNAPSHOT/kotlin-peg-parser-jvm-1.0.0-SNAPSHOT.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "kotlin-peg-parser-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-peg-parser-jvm/1.0.0-SNAPSHOT/kotlin-peg-parser-jvm-1.0.0-SNAPSHOT.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "kotlin-peg-parser-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-peg-parser-linuxx64/1.0.0-SNAPSHOT/kotlin-peg-parser-linuxx64-1.0.0-SNAPSHOT.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "kotlin-peg-parser-linuxx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-peg-parser-linuxx64/1.0.0-SNAPSHOT/kotlin-peg-parser-linuxx64-1.0.0-SNAPSHOT.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "kotlin-peg-parser-linuxx64",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
