{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-peg-parser/1.0.4/kotlin-peg-parser-1.0.4.module",
    "group": "io.github.mirrgieriana.xarpite",
    "module": "kotlin-peg-parser",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-peg-parser-js-1.0.4.klib",
          "url": "kotlin-peg-parser-js-1.0.4.klib",
          "size": 66449,
          "sha512": "d5f53c78c52b0de66498c1217fc08bd4191077634f7d659d936e7ee3cd23c23d148bd4d0aeb45688a9636741c87f7afa87274885aa2edfcbd0a19817f845aea9",
          "sha256": "cadca4c7588b5b48525d6f0d36fd50840e36ade50bbf79a4b553a2d3b5b4ae1c",
          "sha1": "72b1dd6629859acdabb78cc4576231544dc4b2a7",
          "md5": "5a04b2dbcbb67bd98a5ffde311cb8ede"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-peg-parser-js-1.0.4.klib",
          "url": "kotlin-peg-parser-js-1.0.4.klib",
          "size": 66449,
          "sha512": "d5f53c78c52b0de66498c1217fc08bd4191077634f7d659d936e7ee3cd23c23d148bd4d0aeb45688a9636741c87f7afa87274885aa2edfcbd0a19817f845aea9",
          "sha256": "cadca4c7588b5b48525d6f0d36fd50840e36ade50bbf79a4b553a2d3b5b4ae1c",
          "sha1": "72b1dd6629859acdabb78cc4576231544dc4b2a7",
          "md5": "5a04b2dbcbb67bd98a5ffde311cb8ede"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-peg-parser-js-1.0.4-sources.jar",
          "url": "kotlin-peg-parser-js-1.0.4-sources.jar",
          "size": 11861,
          "sha512": "263c491633e52b23a0e88c07fd82ac7be3ee10917bd234ed5150d26ac114811e673bfc68f658d98448a56f749940175a734c20b722d41202211477caab4b1bee",
          "sha256": "17c42e651b0a64df578104b367b6c31e90bc344062cd957f2209519e9bf390a8",
          "sha1": "338b0eac8d45305a88be20caf4c3a3c181998c5c",
          "md5": "097d666d8811da727bd5d54090f67741"
        }
      ]
    }
  ]
}
