{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-peg-parser/1.0.0-SNAPSHOT/kotlin-peg-parser-1.0.0-SNAPSHOT.module",
    "group": "io.github.mirrgieriana.xarpite",
    "module": "kotlin-peg-parser",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-peg-parser-jvm-1.0.0-SNAPSHOT.jar",
          "url": "kotlin-peg-parser-jvm-1.0.0-SNAPSHOT.jar",
          "size": 61925,
          "sha512": "5622aa9d3e233b7446bb72950720a80f796f3d40b0044245487b92dfb2558e811fc86066526cd44cef19b5ac36f1b76e989fc79277fb7fd60cc6b4655a0a8bfb",
          "sha256": "50b9d1a60c776be497587033ac7ffaa0f06fad633e7d9377094454771513b113",
          "sha1": "b0ca7274f37026bb4c9abbf15e810764cd9b5b6f",
          "md5": "076be85726554633220ea76b64e3db5f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-peg-parser-jvm-1.0.0-SNAPSHOT.jar",
          "url": "kotlin-peg-parser-jvm-1.0.0-SNAPSHOT.jar",
          "size": 61925,
          "sha512": "5622aa9d3e233b7446bb72950720a80f796f3d40b0044245487b92dfb2558e811fc86066526cd44cef19b5ac36f1b76e989fc79277fb7fd60cc6b4655a0a8bfb",
          "sha256": "50b9d1a60c776be497587033ac7ffaa0f06fad633e7d9377094454771513b113",
          "sha1": "b0ca7274f37026bb4c9abbf15e810764cd9b5b6f",
          "md5": "076be85726554633220ea76b64e3db5f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-peg-parser-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "kotlin-peg-parser-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 11861,
          "sha512": "263c491633e52b23a0e88c07fd82ac7be3ee10917bd234ed5150d26ac114811e673bfc68f658d98448a56f749940175a734c20b722d41202211477caab4b1bee",
          "sha256": "17c42e651b0a64df578104b367b6c31e90bc344062cd957f2209519e9bf390a8",
          "sha1": "338b0eac8d45305a88be20caf4c3a3c181998c5c",
          "md5": "097d666d8811da727bd5d54090f67741"
        }
      ]
    }
  ]
}
